services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: "pdb"
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pswd}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      #- ./app_logs/postgers/:/var/log/postgresql
    ports:
      - "5432:5432"
      #- "127.0.0.1:5433:5432"
    networks:
      - app-network

  app:
    build: ./code
    container_name: fastapi
    env_file: .env
    volumes:
      - ./code:/app
    ports:
      - "8000:8000"
      #- "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./front
    #volumes:
      #- ./front/:/app/
      #- ./app_logs/frontend:/app/logs  # Логи фронтенда
    ports:
      - 5173:5173
      #- "127.0.0.1:5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - front
    environment:
      - NGINX_HOST=${DOMAIN}
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      #- ./app_logs/nginx/:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge